services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OWNER_ID
        sync: false
      - key: GROUP_ID
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false